### **Reinforcement Learning Programming - CSCN 8020**
#### **Assignment-1**
##### **Prepared by**
- Nikhil Shankar C S
- 9026254

#### **Problem 1**

##### **Markovs Decision Process**

**States** 
- S0 = Idle
- S1 = Move
- S2 = Pick
- S3 = Place

**Actions**
- A0 = Detects object
- A1 = Moves toward object
- A2 = Picks up the object
- A3 = Places the object
- A5 = Returns to rest.

**Rewards**
- R0 = 0
- R1 = f(S0, A0, S1) = 10
- R2 = f(S1, A1, S2) = 10
- R3 = f(S2, A2, S3) = 10
- R4 = f(S3, A3, S4) = 10
- R5 = f(S4, A4, S5) = 10
- R.unknown = f(S.n, A.n, S.x) = -100  ( This last reward function factors for an Action A.n in A0-A5 resulting in an Unknown state or error. This means whenever the picked object is not correctly placed or drops it would result in a negative reward)
> Note : f(S.n, A.n, S.n+1) is the reward function for doing doing Action A.n from State S.n to S.n+1

So MDP for simple pick and place robot can be defined as above:

We can add a transition function denoting the probability of state changes and actions

**Transition Function :**
- P(S.n|S.n+1, A.n) = 0.9 **if** S.n+1 is the intended state **else** 0.1 if S.n+1 is unintended state.
> The above transition function is a naive and basic transition function. We can ideally create a probability function representing errors and abnormalities that can happen at each stage of transition. 

###### **We can also define a Discount factor:** 
**Discount Factor = 0.2**
> This will make sure that the system appreciates immediate rewards over future rewards, which is best for a pick and place robot Since each step is crucial in the final outcome.
Discount factor hence can be assigned as 0.2 so that current reward is given highest priority.





#### **Problem 2**

- Initial Policy is given - always take action UP
- Keeping Discount Factor Gamma = 1 : This makes it easy for calculations.
- Starting with initial Value as 0 for all states.

- Initial Policy says that we can only move up in the first transition: 

#### **Iteration 1**

##### **Value for S1**
- --> Move up from S1 > end up in S1 > Reward = 5
- --> Since initial value of all states are zero > Value(S1) = 5 + (1*0) = 5

##### **Value for S2**
- --> Move up from S2 > End up in S2 > Reward = 10
- --> Since initial value of all states are zero > Value(S2) = 10 + (1*0) = 10

##### **Value for S3**
- --> Move up from S3 > End up in S1 > Reward = 5
- --> Since initial value of all states are zero > Value(S3) = 5 + (1*0) = 5

##### **Value for S4**
- --> Move up from S4 > End up in S2 > Reward = 10
- --> Since initial value of all states are zero > Value(S4) = 10 + (1*0) = 10

- After 1st Iteration Values are

|  |  |
| -- | -- |
| **5** | **10** |
| **5** | **10** |



#### **Iteration 2**

- After first iteration we can choose to do any action from the states

##### **Value for S1 - Iter2**

- **Option Left** 
- --> Move left from S1 > End up in S1 > Reward = 5
- --> Since previous value of S1 = 5 and Gamma = 1 > Value(S1) = 5 + (1 * 5) = 10

- **Option Right** 
- --> Move right from S1 > End up in S2 > Reward = 10
- --> Since previous value of S2 = 10 and Gamma = 1 > Value(S1) = 10 + (1 * 10) = 20

- **Option Up** 
- --> Move up from S1 > End up in S1 > Reward = 5
- --> Since previous value of S1 = 5 and Gamma = 1 > Value(S1) = 5 + (1 * 5) = 10

- **Option Down** 
- --> Move down from S1 > End up in S3 > Reward = 1
- --> Since previous value of S3 = 5 and Gamma = 1 > Value(S1) = 1 + (1 * 5) = 6

- Maximum out of all options
- Max( 10, 20, 10, 6) = 20

- **So Value(S1) after Iteration 2 = 20**


##### **Value for S2 - Iter2**

- **Option Left** 
- --> Move left from S2 > End up in S1 > Reward = 5
- --> Since previous value of S1 = 5 and Gamma = 1 > Value(S2) = 5 + (1 * 5) = 10

- **Option Right** 
- --> Move right from S2 > End up in S2 > Reward = 10
- --> Since previous value of S2 = 10 and Gamma = 1 > Value(S2) = 10 + (1 * 10) = 20

- **Option Up** 
- --> Move up from S2 > End up in S2 > Reward = 10
- --> Since previous value of S2 = 10 and Gamma = 1 > Value(S2) = 10 + (1 * 10) = 20

- **Option Down** 
- --> Move down from S2 > End up in S4 > Reward = 2
- --> Since previous value of S4 = 10 and Gamma = 1 > Value(S2) = 2 + (1 * 10) = 12

- Maximum out of all options
- Max( 10, 20, 20, 12) = 20

- **So Value(S2) after Iteration 2 = 20**



##### **Value for S3 - Iter2**

- **Option Left** 
- --> Move left from S3 > End up in S3 > Reward = 1
- --> Since previous value of S3 = 5 and Gamma = 1 > Value(S3) = 1 + (1 * 5) = 6

- **Option Right** 
- --> Move right from S3 > End up in S4 > Reward = 2
- --> Since previous value of S4 = 10 and Gamma = 1 > Value(S3) = 2 + (1 * 10) = 12

- **Option Up** 
- --> Move up from S3 > End up in S1 > Reward = 5
- --> Since previous value of S1 = 5 and Gamma = 1 > Value(S3) = 5 + (1 * 5) = 10

- **Option Down** 
- --> Move down from S3 > End up in S3 > Reward = 1
- --> Since previous value of S3 = 5 and Gamma = 1 > Value(S3) = 1 + (1 * 5) = 6

- Maximum out of all options
- Max( 6, 12, 10, 6) = 12

- **So Value(S3) after Iteration 2 = 12**



##### **Value for S4 - Iter2**

- **Option Left** 
- --> Move left from S4 > End up in S3 > Reward = 1
- --> Since previous value of S3 = 5 and Gamma = 1 > Value(S4) = 1 + (1 * 5) = 6

- **Option Right** 
- --> Move right from S4 > End up in S4 > Reward = 2
- --> Since previous value of S4 = 10 and Gamma = 1 > Value(S4) = 2 + (1 * 10) = 12

- **Option Up** 
- --> Move up from S4 > End up in S2 > Reward = 10
- --> Since previous value of S2 = 10 and Gamma = 1 > Value(S4) = 10 + (1 * 10) = 20

- **Option Down** 
- --> Move down from S4 > End up in S4 > Reward = 2
- --> Since previous value of S4 = 10 and Gamma = 1 > Value(S4) = 2 + (1 * 10) = 12

- Maximum out of all options
- Max( 6, 12, 20, 12) = 20

- **So Value(S3) after Iteration 2 = 20**

#### **Final Values after Iteration 2 with Gamma ( discount factor of 1)**

|  |  |
| -- | -- |
| **20** | **20** |
| **12** | **20** |

#### **Problem 3**

#### **Baseline Code from Repo**

In [38]:
#!/usr/bin/python3
#!/usr/bin/python3
import numpy as np

class GridWorld():
    def __init__(self, env_size):
        self.env_size = env_size
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)

        # Define the transition probabilities and rewards
        self.actions = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # Right, Left, Down, Up
        self.action_description = ["Right", "Left", "Down", "Up"]

        # Assign a vector of rewards for each of the states
        self.reward = np.ones((self.env_size, self.env_size))*-1
        self.reward[self.terminal_state] = 0

    '''@brief Returns the next state given the chosen action and current state
    '''
    def step(self, action_index, i, j):
        # We are assuming a Transition Probability Matrix where
        # P(s'|s) = 1.0 for a single state and 0 otherwise
        action = self.actions[action_index]
        next_i, next_j = i + action[0], j + action[1]
        if not self.is_valid_state(next_i, next_j):
            next_i, next_j = i, j
        
        done = self.is_terminal_state(next_i, next_j)
        reward = self.reward[next_i, next_j]
        return next_i, next_j, reward, done
    
    '''@brief Checks if a state is within the acceptable bounds of the environment
    '''
    def is_valid_state(self, i, j):
        valid = 0 <= i < self.env_size and 0 <= j < self.env_size
        return valid
    
    '''@brief Returns True if the state is a terminal state
    '''
    def is_terminal_state(self, i, j):
        return (i, j) == self. terminal_state
    
    def get_size(self):
        return self.env_size

    def get_actions(self):
        return self.actions

import numpy as np

class Agent():
    def __init__(self, env, theta_threshold=0.01):
        self.env_size = env.get_size()
        self.env = env
        # Initialize the value function and set terminal state value to 0
        self.V = np.zeros((self.env_size, self.env_size))
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)
        self.V[self.terminal_state] = 0

        self.theta_threshold = theta_threshold

        # Define the transition probabilities and rewards
        self.actions = env.get_actions()  # Right, Left, Down, Up
        self.gamma = 1.0  # Discount factor
        self.pi_greedy = np.zeros((self.env_size, self.env_size), dtype=int)

    '''@brief Calculate the maximim value by following a greedy policy
    '''
    def calculate_max_value(self, i, j):
        # Find the maximum value for the current state using Bellman's equation
        # Start with a - infinite value as the max
        max_value = float('-inf')
        best_action = None
        best_actions_str = ""
        # Loop over all actions
        for action_index in range(len(self.actions)):
          # Find Next state
            next_i, next_j, reward, _ = self.env.step(action_index, i, j)
            if self.env.is_valid_state(next_i, next_j):
                value = self.get_value(next_i, next_j, reward)
                if value >= max_value:
                    # Populating the best_actions description string
                    if value > max_value:
                        best_actions_str = self.env.action_description[action_index]
                    else:
                        best_actions_str += "|" + self.env.action_description[action_index]

                    best_action = action_index
                    max_value = value
        return max_value, best_action, best_actions_str
    
    '''@brief use the Bellman equation to calculate the value of a single state
            Note that the equation is simplified due to the simple transition matrix
    '''
    def get_value(self, i, j, reward):
        return reward + self.gamma * self.V[i, j]
    
    '''
    @brief Overwrites the current state-value function with a new one
    '''
    def update_value_function(self, V):
        self.V = np.copy(V)

    '''
    @brief Returns the full state-value function V_pi
    '''
    def get_value_function(self):
        return self.V

    '''@brief Finds the optimal action for every state and updates the policy
    '''
    def update_greedy_policy(self):
        # Note: We are assuming a greedy deterministic policy
        self.pi_str = []
        for i in range(self.env_size):
            pi_row = []
            for j in range(self.env_size):
                if self.env.is_terminal_state(i,j):
                    pi_row.append("X")
                    continue
                    
                _, self.pi_greedy[i,j], action_str = self.calculate_max_value(i, j)
                pi_row.append(action_str)
            self.pi_str.append(pi_row)
        
    '''@brief Checks if there is the change in V is less than preset threshold
    '''
    def is_done(self, new_V):
        delta = abs(self.V - new_V)
        max_delta = delta.max()
        return max_delta <= self.theta_threshold
    
    '''@brief Returns the stored greedy policy
    '''
    def get_policy(self):
        return self.pi_greedy
    
    '''@brief Prints the policy using the action descriptions
    '''
    def print_policy(self):
        for row in self.pi_str:
            print(row)


def run_mdp():
    ENV_SIZE = 5
    THETA_THRESHOLD = 0.05
    MAX_ITERATIONS = 1000
    env = GridWorld(ENV_SIZE)
    agent = Agent(env, THETA_THRESHOLD)

    # Perform value iteration
    done = False
    for iter in range(MAX_ITERATIONS):
        # Add stopping criteria if change in value function is small
        if done: break
        # Make a copy of the value function
        # TODO: Try in-place state-value function update where Vpi is updated with every state
        new_V = np.copy(agent.get_value_function())
        # Loop over all states
        for i in range(ENV_SIZE):
            for j in range(ENV_SIZE):
                if not env.is_terminal_state(i, j):
                    new_V[i, j], _, _= agent.calculate_max_value(i,j)
        # TODO: Uncomment the next line and compare how many iterations it takes
        # TODO: Change the theta_threshold value to a large value (1.0) and explore what happens to the optimal state-value function and policy
        # done = agent.is_done(new_V)
        agent.update_value_function(new_V)

    # Print the optimal value function
    print("Optimal Value Function Found in %d iterations:"%(iter+1))
    print(agent.get_value_function())

    agent.update_greedy_policy()
    agent.print_policy()

In [5]:
run_mdp()

Optimal Value Function Found in 1000 iterations:
[[-7. -6. -5. -4. -3.]
 [-6. -5. -4. -3. -2.]
 [-5. -4. -3. -2. -1.]
 [-4. -3. -2. -1.  0.]
 [-3. -2. -1.  0.  0.]]
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right', 'Right', 'Right', 'Right', 'X']


#### **Baseline Performance**

In [44]:
import tracemalloc
import time

start_time = time.time()
tracemalloc.start()  # Start memory tracking
 # Record start time
result = run_mdp()
end_time = time.time()  # Record end time
current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

print(f"Execution Time: {end_time - start_time:.6f} seconds")
print(f"Peak Memory Usage: {peak / 1024 / 1024:.6f} MB")

Optimal Value Function Found in 1000 iterations:
[[-7. -6. -5. -4. -3.]
 [-6. -5. -4. -3. -2.]
 [-5. -4. -3. -2. -1.]
 [-4. -3. -2. -1.  0.]
 [-3. -2. -1.  0.  0.]]
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right', 'Right', 'Right', 'Right', 'X']
Execution Time: 0.544410 seconds
Peak Memory Usage: 0.014391 MB


#### **Task1.1 : Update MDP Code**

### Please note that there is an error in the question. The figure in the question has grey areas depicted at (3,0) (1,2) and (0,4) but the reward function definition has it defined as S2,2 S3,0 and S0,4 as Grey areas. **I am taking the reward function definition as the source of truth.**

In [6]:
#!/usr/bin/python3
#!/usr/bin/python3
import numpy as np

class GridWorld():
    def __init__(self, env_size):
        self.env_size = env_size
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)

        # Define the transition probabilities and rewards
        self.actions = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # Right, Left, Down, Up
        self.action_description = ["Right", "Left", "Down", "Up"]

        

        ####### EDITED FOR THE TASK - Nikhil Shankar#####
        ## Incorporating various rewards for the states
        # Assign a vector of rewards for each of the states
        self.reward = np.ones((self.env_size, self.env_size))*-1
        self.reward[self.terminal_state] = 10 
        self.reward[(2,2)] = -5
        self.reward[(3,0)] = -5
        self.reward[(0,4)] = -5
        ####### EDITED FOR THE TASK - Nikhil Shankar#####

    '''@brief Returns the next state given the chosen action and current state
    '''
    def step(self, action_index, i, j):
        # We are assuming a Transition Probability Matrix where
        # P(s'|s) = 1.0 for a single state and 0 otherwise
        action = self.actions[action_index]
        next_i, next_j = i + action[0], j + action[1]
        if not self.is_valid_state(next_i, next_j):
            next_i, next_j = i, j
        
        done = self.is_terminal_state(next_i, next_j)
        reward = self.reward[next_i, next_j]
        return next_i, next_j, reward, done
    
    '''@brief Checks if a state is within the acceptable bounds of the environment
    '''
    def is_valid_state(self, i, j):
        valid = 0 <= i < self.env_size and 0 <= j < self.env_size
        return valid
    
    '''@brief Returns True if the state is a terminal state
    '''
    def is_terminal_state(self, i, j):
        return (i, j) == self. terminal_state
    
    def get_size(self):
        return self.env_size

    def get_actions(self):
        return self.actions

import numpy as np

class Agent():
    def __init__(self, env, theta_threshold=0.01):
        self.env_size = env.get_size()
        self.env = env
        # Initialize the value function and set terminal state value to 0
        self.V = np.zeros((self.env_size, self.env_size))
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)
        self.V[self.terminal_state] = 0

        self.theta_threshold = theta_threshold

        # Define the transition probabilities and rewards
        self.actions = env.get_actions()  # Right, Left, Down, Up
        self.gamma = 1.0  # Discount factor
        self.pi_greedy = np.zeros((self.env_size, self.env_size), dtype=int)

    '''@brief Calculate the maximim value by following a greedy policy
    '''
    def calculate_max_value(self, i, j):
        # Find the maximum value for the current state using Bellman's equation
        # Start with a - infinite value as the max
        max_value = float('-inf')
        best_action = None
        best_actions_str = ""
        # Loop over all actions
        for action_index in range(len(self.actions)):
          # Find Next state
            next_i, next_j, reward, _ = self.env.step(action_index, i, j)
            if self.env.is_valid_state(next_i, next_j):
                value = self.get_value(next_i, next_j, reward)
                if value >= max_value:
                    # Populating the best_actions description string
                    if value > max_value:
                        best_actions_str = self.env.action_description[action_index]
                    else:
                        best_actions_str += "|" + self.env.action_description[action_index]

                    best_action = action_index
                    max_value = value
        return max_value, best_action, best_actions_str
    
    '''@brief use the Bellman equation to calculate the value of a single state
            Note that the equation is simplified due to the simple transition matrix
    '''
    def get_value(self, i, j, reward):
        return reward + self.gamma * self.V[i, j]
    
    '''
    @brief Overwrites the current state-value function with a new one
    '''
    def update_value_function(self, V):
        self.V = np.copy(V)

    '''
    @brief Returns the full state-value function V_pi
    '''
    def get_value_function(self):
        return self.V

    '''@brief Finds the optimal action for every state and updates the policy
    '''
    def update_greedy_policy(self):
        # Note: We are assuming a greedy deterministic policy
        self.pi_str = []
        for i in range(self.env_size):
            pi_row = []
            for j in range(self.env_size):
                if self.env.is_terminal_state(i,j):
                    pi_row.append("X")
                    continue
                    
                _, self.pi_greedy[i,j], action_str = self.calculate_max_value(i, j)
                pi_row.append(action_str)
            self.pi_str.append(pi_row)
        
    '''@brief Checks if there is the change in V is less than preset threshold
    '''
    def is_done(self, new_V):
        delta = abs(self.V - new_V)
        max_delta = delta.max()
        return max_delta <= self.theta_threshold
    
    '''@brief Returns the stored greedy policy
    '''
    def get_policy(self):
        return self.pi_greedy
    
    '''@brief Prints the policy using the action descriptions
    '''
    def print_policy(self):
        for row in self.pi_str:
            print(row)


def run_mdp():
    ENV_SIZE = 5
    THETA_THRESHOLD = 0.05
    MAX_ITERATIONS = 1000
    env = GridWorld(ENV_SIZE)
    agent = Agent(env, THETA_THRESHOLD)

    # Perform value iteration
    done = False
    for iter in range(MAX_ITERATIONS):
        # Add stopping criteria if change in value function is small
        if done: break
        # Make a copy of the value function
        # TODO: Try in-place state-value function update where Vpi is updated with every state
        new_V = np.copy(agent.get_value_function())
        # Loop over all states
        for i in range(ENV_SIZE):
            for j in range(ENV_SIZE):
                if not env.is_terminal_state(i, j):
                    new_V[i, j], _, _= agent.calculate_max_value(i,j)
        # TODO: Uncomment the next line and compare how many iterations it takes
        # TODO: Change the theta_threshold value to a large value (1.0) and explore what happens to the optimal state-value function and policy
        # done = agent.is_done(new_V)
        agent.update_value_function(new_V)

    # Print the optimal value function
    print("Optimal Value Function Found in %d iterations:"%(iter+1))
    print(agent.get_value_function())

    agent.update_greedy_policy()
    agent.print_policy()

In [7]:
run_mdp()

Optimal Value Function Found in 1000 iterations:
[[ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]
 [ 5.  6.  7.  8.  9.]
 [ 6.  7.  8.  9. 10.]
 [ 7.  8.  9. 10.  0.]]
['Right|Down', 'Right|Down', 'Right|Down', 'Down', 'Down']
['Right|Down', 'Right|Down', 'Right', 'Right|Down', 'Down']
['Right', 'Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right', 'Right', 'Right', 'Right', 'X']


- Modified the code to add the reward functions as described in the question can be found in GridWorld class.
```python 
####### EDITED FOR THE TASK - Nikhil Shankar#####
        ## Incorporating various rewards for the states
        # Assign a vector of rewards for each of the states
        self.reward = np.ones((self.env_size, self.env_size))*-1
        self.reward[self.terminal_state] = 10 
        self.reward[(2,2)] = -5
        self.reward[(3,0)] = -5
        self.reward[(0,4)] = -5
####### EDITED FOR THE TASK - Nikhil Shankar#####
```

> The modified code can be found in the GridWorld class.


- If you see the Policy output between the previous output and the one above you can see the difference.
- Check policy for (1,2). Before rewards it was **Right|Down** after incorporating rewards it is **Right** which is better since if we move down we end up in a gray state which we want to avoid.

##### **Task 3.1.1 Value Table**

| | | | | |
|-|-|-|-|-| 
| 3 | 4 | 5 | 6 | 7 |
| 4 | 5 | 6 | 7 | 8 |
| 5 | 6 | 7 | 8 | 9 |
| 6 | 7 | 8 | 9 | 10 |
| 7 | 8 | 9 | 10 | 0 |

##### **Task 3.1.2 Policy Table**

| | | | | |
|-|-|-|-|-| 
|'Right/Down' | 'Right/Down' | 'Right/Down' | 'Down' | 'Down'|
|'Right/Down' | 'Right/Down' | 'Right' | 'Right/Down' | 'Down'|
|'Right' | 'Down' | 'Right/Down' | 'Right/Down' | 'Down' |
| 'Right|Down' | 'Right/Down' | 'Right/Down' | 'Right/Down' | 'Down' |
| 'Right' | 'Right' | 'Right' | 'Right' | 'X' |

#### **Problem 3: Task 2 : Value Iteration Variations**

In [21]:
#!/usr/bin/python3
#!/usr/bin/python3
import numpy as np

class GridWorld():
    def __init__(self, env_size):
        self.env_size = env_size
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)

        # Define the transition probabilities and rewards
        self.actions = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # Right, Left, Down, Up
        self.action_description = ["Right", "Left", "Down", "Up"]

        

        ####### EDITED FOR THE TASK - Nikhil Shankar#####
        ## Incorporating various rewards for the states
        # Assign a vector of rewards for each of the states
        self.reward = np.ones((self.env_size, self.env_size))*-1
        self.reward[self.terminal_state] = 10 
        self.reward[(2,2)] = -5
        self.reward[(3,0)] = -5
        self.reward[(0,4)] = -5
        ####### EDITED FOR THE TASK - Nikhil Shankar#####

    '''@brief Returns the next state given the chosen action and current state
    '''
    def step(self, action_index, i, j):
        # We are assuming a Transition Probability Matrix where
        # P(s'|s) = 1.0 for a single state and 0 otherwise
        action = self.actions[action_index]
        next_i, next_j = i + action[0], j + action[1]
        if not self.is_valid_state(next_i, next_j):
            next_i, next_j = i, j
        
        done = self.is_terminal_state(next_i, next_j)
        reward = self.reward[next_i, next_j]
        return next_i, next_j, reward, done
    
    '''@brief Checks if a state is within the acceptable bounds of the environment
    '''
    def is_valid_state(self, i, j):
        valid = 0 <= i < self.env_size and 0 <= j < self.env_size
        return valid
    
    '''@brief Returns True if the state is a terminal state
    '''
    def is_terminal_state(self, i, j):
        return (i, j) == self. terminal_state
    
    def get_size(self):
        return self.env_size

    def get_actions(self):
        return self.actions

import numpy as np

class Agent():
    def __init__(self, env, theta_threshold=0.01):
        self.env_size = env.get_size()
        self.env = env
        # Initialize the value function and set terminal state value to 0
        self.V = np.zeros((self.env_size, self.env_size))
        # TODO: Change the location of the terminal state and check how the optimal policy changes
        # TODO: Add more than one terminal state (requires more changes in the code)
        self.terminal_state = (4, 4)
        self.V[self.terminal_state] = 0

        self.theta_threshold = theta_threshold

        # Define the transition probabilities and rewards
        self.actions = env.get_actions()  # Right, Left, Down, Up
        self.gamma = 1.0  # Discount factor
        self.pi_greedy = np.zeros((self.env_size, self.env_size), dtype=int)

    '''@brief Calculate the maximim value by following a greedy policy
    '''
    def calculate_max_value(self, i, j):
        # Find the maximum value for the current state using Bellman's equation
        # Start with a - infinite value as the max
        max_value = float('-inf')
        best_action = None
        best_actions_str = ""
        # Loop over all actions
        for action_index in range(len(self.actions)):
          # Find Next state
            next_i, next_j, reward, _ = self.env.step(action_index, i, j)
            if self.env.is_valid_state(next_i, next_j):
                value = self.get_value(next_i, next_j, reward)
                if value >= max_value:
                    # Populating the best_actions description string
                    if value > max_value:
                        best_actions_str = self.env.action_description[action_index]
                    else:
                        best_actions_str += "|" + self.env.action_description[action_index]

                    best_action = action_index
                    max_value = value
        return max_value, best_action, best_actions_str
    
    '''@brief use the Bellman equation to calculate the value of a single state
            Note that the equation is simplified due to the simple transition matrix
    '''
    def get_value(self, i, j, reward):
        return reward + self.gamma * self.V[i, j]
    
    '''
    @brief Overwrites the current state-value function with a new one
    '''
    def update_value_function(self, V):
        self.V = np.copy(V)

    '''
    @brief Returns the full state-value function V_pi
    '''
    def get_value_function(self):
        return self.V

    '''@brief Finds the optimal action for every state and updates the policy
    '''
    def update_greedy_policy(self):
        # Note: We are assuming a greedy deterministic policy
        self.pi_str = []
        for i in range(self.env_size):
            pi_row = []
            for j in range(self.env_size):
                if self.env.is_terminal_state(i,j):
                    pi_row.append("X")
                    continue
                    
                _, self.pi_greedy[i,j], action_str = self.calculate_max_value(i, j)
                pi_row.append(action_str)
            self.pi_str.append(pi_row)
        
    '''@brief Checks if there is the change in V is less than preset threshold
    '''
    def is_done(self, new_V):
        delta = abs(self.V - new_V)
        max_delta = delta.max()
        return max_delta <= self.theta_threshold
    
    '''@brief Returns the stored greedy policy
    '''
    def get_policy(self):
        return self.pi_greedy
    
    '''@brief Prints the policy using the action descriptions
    '''
    def print_policy(self):
        for row in self.pi_str:
            print(row)


def run_mdp():
    print("Running problem 3 task 2")
    ENV_SIZE = 5
    THETA_THRESHOLD = 0.05
    MAX_ITERATIONS = 1000
    env = GridWorld(ENV_SIZE)
    agent = Agent(env, THETA_THRESHOLD)

    # Perform value iteration
    done = False
    for iter in range(MAX_ITERATIONS):
        # Add stopping criteria if change in value function is small
        if done: break
        # Make a copy of the value function
        # TODO: Try in-place state-value function update where Vpi is updated with every state
        #new_V = np.copy(agent.get_value_function())
        # Loop over all states

        ### Updated code for task problem 3 task 2
        for i in range(ENV_SIZE):
            for j in range(ENV_SIZE):
                if not env.is_terminal_state(i, j):
                    #if i == 2 and j == 2:
                        #print(f"Before {agent.get_value_function()[i, j]}")
                    agent.get_value_function()[i, j], _, _= agent.calculate_max_value(i,j)
                    #if i == 2 and j == 2:
                        #print(f"After {agent.get_value_function()[i, j]}")
        ### Updated code for task problem 3 task 2
        # TODO: Uncomment the next line and compare how many iterations it takes
        # TODO: Change the theta_threshold value to a large value (1.0) and explore what happens to the optimal state-value function and policy
        # done = agent.is_done(new_V)
        #agent.update_value_function(new_V)

    # Print the optimal value function
    print("Optimal Value Function Found in %d iterations:"%(iter+1))
    print(agent.get_value_function())

    agent.update_greedy_policy()
    agent.print_policy()

In [31]:
import time

run_mdp()


Running problem 3 task 2
Optimal Value Function Found in 1000 iterations:
[[ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]
 [ 5.  6.  7.  8.  9.]
 [ 6.  7.  8.  9. 10.]
 [ 7.  8.  9. 10.  0.]]
['Right|Down', 'Right|Down', 'Right|Down', 'Down', 'Down']
['Right|Down', 'Right|Down', 'Right', 'Right|Down', 'Down']
['Right', 'Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right', 'Right', 'Right', 'Right', 'X']


- Updating the value function to update immediately after each value state updation doesn't seem to affect the outcome.
- Code changes 

```python
### Updated code for task problem 3 task 2
       for i in range(ENV_SIZE):
            for j in range(ENV_SIZE):
                if not env.is_terminal_state(i, j):
                    if i == 2 and j == 2:
                        print(f"Before {agent.get_value_function()[i, j]}")
                    agent.get_value_function()[i, j], _, _= agent.calculate_max_value(i,j)
                    if i == 2 and j == 2:
                        print(f"After {agent.get_value_function()[i, j]}")
### Updated code for task problem 3 task 2
```

- Added the print statement to check and verify that the value function is getting updated inplace and to avoid printing a lot of statements added i == 2 and j == 2 check as well.
- We are updating the value function inside the loop iteration itself. Previously it was done outside the loop.

#### **Calculate time and Memory usage**

In [46]:
import tracemalloc

start_time = time.time()
tracemalloc.start()  # Start memory tracking
 # Record start time
result = run_mdp()
end_time = time.time()  # Record end time
current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

print(f"Execution Time: {end_time - start_time:.6f} seconds")
print(f"Peak Memory Usage: {peak / 1024 / 1024:.6f} MB")

Running problem 3 task 2
Optimal Value Function Found in 1000 iterations:
[[ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]
 [ 5.  6.  7.  8.  9.]
 [ 6.  7.  8.  9. 10.]
 [ 7.  8.  9. 10.  0.]]
['Right|Down', 'Right|Down', 'Right|Down', 'Down', 'Down']
['Right|Down', 'Right|Down', 'Right', 'Right|Down', 'Down']
['Right', 'Down', 'Right|Down', 'Right|Down', 'Down']
['Right|Down', 'Right|Down', 'Right|Down', 'Right|Down', 'Down']
['Right', 'Right', 'Right', 'Right', 'X']
Execution Time: 0.549248 seconds
Peak Memory Usage: 0.014581 MB


- Both takes around ~0.54 seconds and ~0.014MB 
- There was no significant improvements in time nor Memory usage after doing the calculations in place.
- Ideally we should have gained some memory improvements due to the inplace calculations we have done.

#### **Problem 4 - Task 1**

In [36]:
import numpy as np
from collections import defaultdict

class GridWorld:
    def __init__(self):
        self.grid_size = 5
        self.goal = (4, 4)
        self.holes = [(3, 0), (2, 2), (0, 4)]
        # Action indices: 0=right, 1=down, 2=left, 3=up
        self.actions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        
    def get_reward(self, state, next_state):
        if next_state == self.goal:
            return 10
        elif next_state in self.holes:
            return -5
        return -1
    
    def is_terminal(self, state):
        return state == self.goal or state in self.holes
    
    def next_state(self, state, action):
        x, y = state
        dx, dy = action
        next_x, next_y = x + dx, y + dy
        
        # If the next position would be outside the grid, stay in current position
        if not (0 <= next_x < self.grid_size and 0 <= next_y < self.grid_size):
            return state
            
        return (next_x, next_y)

def epsilon_greedy_policy(Q, state, epsilon=0.1):
    if np.random.random() < epsilon:
        return np.random.randint(4)
    else:
        return np.argmax(Q[state])

def generate_episode(env, Q, epsilon):
    episode = []
    state = (0, 0)  # Start state
    
    while not env.is_terminal(state):
        # Choose action using epsilon-greedy policy
        action_idx = epsilon_greedy_policy(Q, state, epsilon)
        action = env.actions[action_idx]
        
        # Take action and observe next state and reward
        next_state = env.next_state(state, action)
        reward = env.get_reward(state, next_state)
        
        episode.append((state, action_idx, reward, next_state))
        state = next_state
        
        if len(episode) > 100:  # Prevent infinite loops
            break
            
    return episode

def monte_carlo_off_policy(num_episodes=5000, gamma=0.9, epsilon=0.1):
    env = GridWorld()
    
    # Initialize Q-values and returns
    Q = defaultdict(lambda: np.zeros(len(env.actions)))
    returns = defaultdict(list)  # Store returns for each state-action pair
    
    for episode in range(num_episodes):
        # Generate episode using epsilon-greedy policy
        trajectory = generate_episode(env, Q, epsilon)
        
        # Calculate returns for each step
        G = 0
        for t in range(len(trajectory)-1, -1, -1):
            state, action, reward, next_state = trajectory[t]
            G = gamma * G + reward
            
            # Store return for this state-action pair
            state_action = (state, action)
            returns[state_action].append(G)
            
            # Update Q-value with average return
            Q[state][action] = np.mean(returns[state_action])
    
    # Create deterministic policy from Q-values
    policy = {}
    for state in Q.keys():
        policy[state] = np.argmax(Q[state])
    
    return Q, policy

# Run the algorithm
Q, policy = monte_carlo_off_policy(num_episodes=20000, gamma=0.9, epsilon=0.1)

def print_policy_and_grid(policy, grid_size=5):
    arrows = ['→', '↓', '←', '↑']
    print("\nGrid Layout and Policy:")
    print("-" * (grid_size * 2 + 1))
    
    for i in range(grid_size):
        print("|", end="")
        for j in range(grid_size):
            if (i, j) == (4, 4):
                print("G", end="|")
            elif (i, j) in [(3, 0), (2, 2), (0, 4)]:
                print("H", end="|")
            else:
                if (i, j) in policy:
                    print(arrows[policy[(i, j)]], end="|")
                else:
                    print(" ", end="|")
        print("\n" + "-" * (grid_size * 2 + 1))

# Print the learned policy
print_policy_and_grid(policy)

def print_q_values(Q, state=(0, 0)):
    print(f"\nQ-values for state {state}:")
    actions = ['Right', 'Down', 'Left', 'Up']
    for i, action in enumerate(actions):
        print(f"{action}: {Q[state][i]:.2f}")



Grid Layout and Policy:
-----------
|→|→|→|↓|H|
-----------
|→|→|→|↓|←|
-----------
|↓|↑|H|↓|↓|
-----------
|H|↓|↓|↓|↓|
-----------
|→|→|→|→|G|
-----------


In [42]:
for i in range(0, 5):
    print(f"Row {i}")
    for j in range(0,5):
        value = Q[(i,j)]
        print(f"| {value} |")
    print("\n")

Row 0
| [-1.42953202 -2.77273959 -2.87170114 -4.4528316 ] |
| [-0.36432429 -1.12715391 -2.87431111 -1.6702724 ] |
| [ 0.79891891  0.66575352 -1.54286064 -0.62582355] |
| [-5.          2.28465252 -0.33298404  0.77624611] |
| [0. 0. 0. 0.] |


Row 1
| [-1.02359178 -7.07926226 -8.28196816 -7.82454021] |
| [ 0.81248739 -2.14713743 -3.21694826 -1.5892916 ] |
| [ 2.27627236 -5.         -0.82901674 -0.22466618] |
| [0.92556978 3.87983075 0.70519031 0.72438273] |
| [-2.37140424  1.40555175  2.35516086 -5.        ] |


Row 2
| [-6.93678084 -5.         -6.92624904 -8.97153745] |
| [-5.         -3.43869148 -7.74875921 -0.72403472] |
| [0. 0. 0. 0.] |
| [ 4.02359917  5.82128794 -5.          2.19698384] |
| [-5.16808381  7.66142818  3.71711027 -1.11875503] |


Row 3
| [0. 0. 0. 0.] |
| [-2.7096572  3.84128    0.         0.       ] |
| [ 4.58007618  5.77019702  2.457152   -5.        ] |
| [7.60117184 7.76861977 4.02809698 3.82709756] |
| [-1.62290427 10.          6.2         3.2604497 ] |


Row 4
| 

- We printed the value function for all actions in each state. We can see that the action with the highest value is what we need to take at each step.

- eg. In Row4 4th entry = S(4,3) = [10.          7.72437863  5.81750479  5.83926406]

- Ideally condition the action to be taken is to move right from there to reach the goal. 
```python
self.actions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
```
- This is the definiton of our actions. And checking the values for S(4,3) we can see that the highest value is correctly assigned to the action **Right** which is 10.

- Now we can go ahead and output value function for each state and corresponding action


In [53]:
def print_arg_max_value(Q):
    for i in range(0, 5):
        val = "| "
        for j in range(0,5):
            value = np.max(Q[(i,j)])
            val += f" {round(value,2)} "
        print(val + " |")

In [54]:
print("Optimal Actions")
print_policy_and_grid(policy)

print("Optimal Value function")
print_arg_max_value(Q)

Optimal Actions

Grid Layout and Policy:
-----------
|→|→|→|↓|H|
-----------
|→|→|→|↓|←|
-----------
|↓|↑|H|↓|↓|
-----------
|H|↓|↓|↓|↓|
-----------
|→|→|→|→|G|
-----------
Optimal Value function
|  -1.43  -0.36  0.8  2.28  0.0  |
|  -1.02  0.81  2.28  3.88  2.36  |
|  -5.0  -0.72  0.0  5.82  7.66  |
|  0.0  3.84  5.77  7.77  10.0  |
|  4.58  5.78  7.75  10.0  0.0  |


#### **Comparison Monte carlo vs Markov Decision Process** 

- Monte carlo method took drastically higher time to find the optimal output
- Monte carlo took ~90 seconds while MDP was able to do that in less than a second.
- With smaller number of episodes Monte Carlo struggled to arrive at the optimum policy. ( Tried with 1000, 5000 and 10000)
- So computationally Monte Carlo is inferior to MDP method.
- Monte carlo can work even without reward (We have used rewards for our use case ) or probabilities whereas MDP requires it.
- MC is useful when model dynamics are difficult to define.
- MDP is quick but it require model and environment dynamics so it is suited to solve problems which are well defined.

